"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHANNEL_SETUP = exports.BOT_ID = exports.MOD_ROLE_ID = exports.SUPPORT_CATEGORY = exports.TOKEN = void 0;
require('dotenv').config({ path: require('find-config')('.env') });
var TOKEN = process.env.TOKEN;
exports.TOKEN = TOKEN;
var SUPPORT_CATEGORY = process.env.SUPPORT_CATEGORY;
exports.SUPPORT_CATEGORY = SUPPORT_CATEGORY;
var CHANNEL_SETUP = process.env.CHANNEL_SETUP;
exports.CHANNEL_SETUP = CHANNEL_SETUP;
var MOD_ROLE_ID = process.env.MOD_ROLE_ID;
exports.MOD_ROLE_ID = MOD_ROLE_ID;
var BOT_ID = process.env.BOT_ID;
exports.BOT_ID = BOT_ID;
